server:
  port: 9191

spring:
  main:
    allow-bean-definition-overriding: true

keycloak:
  realm: marketplace
  auth-server-url: http://localhost:8081/auth
  ssl-required: external
  resource: umico
  bearer-only: true
  use-resource-role-mappings: true
  principal-attribute: preferred_username